# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QGISLeafletPackage
                                 A QGIS plugin
 Export your project to a leaflet webpage/app with data stored in a geopackage.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-01
        copyright            : (C) 2022 by Peace
        email                : peacester@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QGISLeafletPackage class from file QGISLeafletPackage.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    
    from .saveproject import QGISLeafletPackage
    return QGISLeafletPackage(iface)
